console.log("Checking imports...");
import { enqueueEncompassRetrievalJob } from "../src/features/bom/services/retrieval-job-store";
console.log("retrieval-job-store imported");
import { runRetrievalWorker } from "../src/features/bom/services/retrieval-worker";
console.log("retrieval-worker imported");
import { createOrReuseBomJob } from "../src/features/bom/services/job-store";
console.log("job-store imported");
import { db } from "../src/server/db";
console.log("db imported");
import { bomRetrievalJobs } from "../src/server/db/schema/bom-retrieval-jobs";
console.log("bom-retrieval-jobs schema imported");
console.log("All imports successful!");
