import type { PromptScenario } from "./types";
import {
  BOM_ROW_EXTRACTION_JSON_PROMPT,
  COMPUTER_USE_NAVIGATION_PROMPT,
  NAMEPLATE_OCR_IDENTITY_JSON_PROMPT,
  OFFICIAL_PARTS_SOURCE_SEARCH_PROMPT,
  PLAINTEXT_IDENTITY_EXTRACTOR_PROMPT,
  PRICING_ROUTER_PROMPT,
  TECHNICAL_DIAGRAM_CALLOUT_CSV_PROMPT,
  VERIFIED_RETAIL_PRICING_PROMPT,
  VISUAL_QA_DRIFT_JSON_PROMPT,
} from "../prompts/strict-scenarios";
import {
  MAY7_GLOBAL_RLD_PROMPT_RULE,
  MAY7_RLD_ORCHESTRATION_PHASE_1A_PROMPT,
  MAY7_ROADRUNNER_DIAGNOSTIC_PROMPT,
  MAY7_ROADRUNNER_FINAL_BOM_AUDIT_PROMPT,
  MAY7_ROADRUNNER_IDENTITY_EXTRACTION_PROMPT,
  MAY7_ROADRUNNER_ORCHESTRATOR_PROMPT,
  MAY7_ROADRUNNER_PARTS_EXTRACTION_PROMPT,
  MAY7_ROADRUNNER_PRICING_EXTRACTION_PROMPT,
  MAY7_TATTOO_FLASH_VARIANT_SHEET_PROMPT,
  MAY7_TATTOO_SURGICAL_EDIT_PROMPT,
  MAY7_UNIFIED_IMAGE_TATTOO_LOCK_EXTRACTION_PROMPT,
} from "../prompts/may7-rld-prompts";

export const PROMPT_SCENARIOS: PromptScenario[] = [
  {
    id: "identity-extraction",
    name: "Identity Extraction",
    type: "identity_extraction",
    description: "Extract appliance identity from OCR, manual, supplier, or operator-entered evidence.",
    requiredInputs: ["imageOcrText", "manualText", "knownSupplierResult", "userEnteredModelNumber"],
    enabled: true,
    systemPrompt: [
      "You are a strict appliance identity extraction agent.",
      "Return only valid JSON.",
      "Do not infer brand, model, serial, product type, or engineering code unless evidence supports it.",
      "Use null for unknown values and include confidence by field.",
    ].join("\n"),
    userPromptTemplate: [
      "Extract brand, model number, serial number, product type, engineering code, confidence, and candidates.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      modelNumber: null,
      serialNumber: null,
      productType: null,
      engineeringCode: null,
      confidence: {
        brand: 0,
        modelNumber: 0,
        serialNumber: 0,
        productType: 0,
        engineeringCode: 0,
      },
      candidates: [],
    },
  },
  {
    id: "nameplate-ocr-identity-json",
    name: "Nameplate OCR Identity Extraction",
    type: "nameplate_ocr_identity_json",
    description: "Extract only visible brand, product type, model number, and serial number from one nameplate image.",
    requiredInputs: ["nameplateImage"],
    enabled: true,
    systemPrompt: NAMEPLATE_OCR_IDENTITY_JSON_PROMPT,
    userPromptTemplate: [
      "Run the strict nameplate OCR identity extraction contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      productType: null,
      modelNumber: null,
      serialNumber: null,
    },
  },
  {
    id: "plaintext-identity-extractor",
    name: "Plaintext Identity Extractor",
    type: "plaintext_identity_extraction",
    description: "Convert plaintext appliance evidence into a bounded RoadrunnerParts identity object.",
    requiredInputs: ["plaintextEvidence"],
    enabled: true,
    systemPrompt: PLAINTEXT_IDENTITY_EXTRACTOR_PROMPT,
    userPromptTemplate: [
      "Extract identity from the supplied plaintext evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      model: null,
      serial: null,
      type_code: null,
      appliance_type: null,
      fuel_type: null,
      voltage_or_power_clues: [],
    },
  },
  {
    id: "supplier-url-generation",
    name: "Supplier URL Generation",
    type: "supplier_url_generation",
    description: "Convert brand/model context into supplier-specific candidate URLs.",
    requiredInputs: ["brand", "modelNumber", "supplier", "knownUrlRules"],
    enabled: true,
    systemPrompt: [
      "You are a supplier URL planning agent.",
      "Return only valid JSON.",
      "Do not browse or claim a URL is live unless the input evidence proves it.",
      "Treat URLs as candidates for later operator review.",
    ].join("\n"),
    userPromptTemplate: [
      "Generate supplier-specific search URLs and canonical model URL candidates.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      supplier: "encompass",
      brandCode: null,
      normalizedModel: null,
      candidateUrls: [],
      confidence: 0,
      notes: [],
    },
  },
  {
    id: "official-parts-source-search",
    name: "Official Parts Source Search",
    type: "official_parts_source_search",
    description: "Select one verified model-specific URL from a target supplier domain.",
    requiredInputs: ["modelNumber", "targetSupplierDomain"],
    enabled: true,
    systemPrompt: OFFICIAL_PARTS_SOURCE_SEARCH_PROMPT,
    userPromptTemplate: [
      "Identify the single best model-specific URL from the target domain.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: "https://target-domain.example/model-specific-url",
  },
  {
    id: "diagram-discovery",
    name: "Diagram Discovery",
    type: "diagram_discovery",
    description: "Plan diagram section discovery from source context without extracting final parts.",
    requiredInputs: ["modelNumber", "supplier", "sourceUrl", "sourceUrls", "candidateUrls", "browserCapture"],
    enabled: true,
    systemPrompt: [
      "You are a diagram discovery reviewer.",
      "Return only valid JSON.",
      "Use only supplied source context.",
      "Accept multiple source URLs. Treat sourceUrl as the primary candidate and sourceUrls/candidateUrls as the ordered discovery queue.",
      "URL Context may include up to 20 URLs. Preserve the queue order and do not collapse it to one URL unless only one URL was supplied.",
      "Function calling is not capped by call count; obey the selected tool policy and stage contract.",
      "Do not discard secondary URLs unless source evidence proves they are the wrong model or wrong supplier.",
      "Do not create final BOM rows or part-number claims.",
    ].join("\n"),
    userPromptTemplate: [
      "Find diagram sections and source URLs from the supplied evidence.",
      "If multiple URLs are provided, review them in priority order and return every usable diagram URL with its originating source URL.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      modelNumber: null,
      supplier: null,
      sourceUrlsReviewed: [],
      diagrams: [
        {
          sectionName: null,
          diagramUrl: null,
          sourceUrl: null,
          confidence: 0,
        },
      ],
    },
  },
  {
    id: "technical-diagram-callouts-csv",
    name: "Technical Diagram Extraction",
    type: "technical_diagram_callouts_csv",
    description: "Extract a top-left sheet title and unique visible numeric callouts from one technical diagram image as CSV.",
    requiredInputs: ["diagramImage"],
    enabled: true,
    systemPrompt: TECHNICAL_DIAGRAM_CALLOUT_CSV_PROMPT,
    userPromptTemplate: [
      "Run the strict technical diagram extraction contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: "Sheet_Title,Callout_Number\nFRONT PANEL & DOOR,313",
  },
  {
    id: "visual-qa-drift-json",
    name: "Visual QA Drift Check",
    type: "visual_qa_drift_json",
    description: "Read-only comparison of a candidate generated image against a base reference image.",
    requiredInputs: ["baseReferenceImage", "candidateGeneratedImage"],
    enabled: true,
    systemPrompt: VISUAL_QA_DRIFT_JSON_PROMPT,
    userPromptTemplate: [
      "Run the read-only visual QA and design drift check.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      passed: false,
      major_drift_detected: false,
      added_elements: [],
      missing_elements: [],
      altered_elements: [],
      proportion_changes: [],
      notes: [],
    },
  },
  {
    id: "computer-use-navigation",
    name: "Computer-Use UI Navigation",
    type: "computer_use_navigation",
    description: "Navigate a current browser/DOM state to an assembly page and return the first three visible parts, or a blocked reason.",
    requiredInputs: ["browserViewport", "domState", "modelPageUrl"],
    enabled: true,
    systemPrompt: COMPUTER_USE_NAVIGATION_PROMPT,
    userPromptTemplate: [
      "Run the deterministic UI navigation contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: "1. Exact visible part text\n2. Exact visible part text\n3. Exact visible part text",
  },
  {
    id: "bom-extraction",
    name: "BOM Extraction",
    type: "bom_extraction",
    description: "Extract source-backed part rows from supplied provider/manual evidence only.",
    requiredInputs: ["modelNumber", "supplier", "sourceUrl", "diagramContext", "sourceEvidence"],
    enabled: true,
    systemPrompt: [
      "You are a source-backed BOM extraction agent.",
      "Return only valid JSON.",
      "Final part rows must come from supplied provider evidence, captured JSON, manuals, or database records.",
      "Do not treat prompts, appliance architecture, or guesses as source evidence.",
    ].join("\n"),
    userPromptTemplate: [
      "Extract part title, part number, quantity, diagram key, assembly section, source URL, and evidence text.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      modelNumber: null,
      supplier: null,
      parts: [
        {
          partNumber: null,
          partTitle: null,
          quantity: null,
          diagramKey: null,
          assemblySection: null,
          sourceUrl: null,
          evidenceText: null,
          confidence: 0,
        },
      ],
      completeness: {
        expectedCount: null,
        actualCount: 0,
        status: "no_result",
      },
    },
  },
  {
    id: "bom-row-extraction-json",
    name: "BOM Row Extraction JSON",
    type: "bom_row_extraction_json",
    description: "Extract model-specific BOM rows from supplied model, diagram, and pricing evidence without inventing missing data.",
    requiredInputs: ["modelSpecificPartsEvidence", "diagramCalloutEvidence", "pricingEvidence"],
    enabled: true,
    systemPrompt: BOM_ROW_EXTRACTION_JSON_PROMPT,
    userPromptTemplate: [
      "Extract strict source-backed BOM rows from the supplied evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      model_number: "",
      appliance_type: null,
      bom_rows: [
        {
          sheet_title: null,
          callout_number: null,
          part_number: null,
          part_title: null,
          quantity: null,
          price: null,
          availability: null,
          source_name: "",
          source_url: null,
          confidence: "model_confirmed",
        },
      ],
    },
  },
  {
    id: "bom-validation",
    name: "BOM Validation",
    type: "bom_validation",
    description: "Validate rows before database, export, pricing, or listing actions.",
    requiredInputs: ["brand", "modelNumber", "rows", "retrievalStatus"],
    enabled: true,
    systemPrompt: [
      "You are a BOM validation gate.",
      "Return only valid JSON.",
      "Do not repair rows by inventing missing evidence.",
      "Reject rows missing source URL or required part identity.",
    ].join("\n"),
    userPromptTemplate: [
      "Validate extracted rows before anything enters a database or export pipeline.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      valid: false,
      errors: [],
      warnings: [],
      acceptedRows: [],
      rejectedRows: [],
    },
  },
  {
    id: "pricing-reconciliation",
    name: "Pricing Reconciliation",
    type: "pricing_reconciliation",
    description: "Attach supplier pricing only after BOM rows are validated.",
    requiredInputs: ["partNumber", "supplier", "validatedBomRow", "pricingSourceEvidence"],
    enabled: true,
    systemPrompt: [
      "You are a pricing reconciliation agent.",
      "Return only valid JSON.",
      "Do not price unvalidated BOM rows.",
      "Do not invent price, availability, or supplier evidence.",
    ].join("\n"),
    userPromptTemplate: [
      "Attach supplier pricing from supplied pricing evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      partNumber: null,
      supplier: null,
      price: null,
      availability: null,
      sourceUrl: null,
      confidence: 0,
    },
  },
  {
    id: "pricing-router",
    name: "Fallback Pricing Router",
    type: "pricing_router",
    description: "Choose the best pricing source tier using the strict fallback order.",
    requiredInputs: ["brand", "modelNumber", "partNumber", "supplierList"],
    enabled: true,
    systemPrompt: PRICING_ROUTER_PROMPT,
    userPromptTemplate: [
      "Choose the selected pricing source tier and explain the source-bound reason.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      selected_tier: null,
      selected_source: null,
      reason: "",
    },
  },
  {
    id: "verified-retail-pricing",
    name: "Verified Retail Pricing",
    type: "retail_pricing_verification",
    description: "Verify candidate retail prices against exact part and model context.",
    requiredInputs: ["partNumber", "modelNumber", "candidatePricingSources"],
    enabled: true,
    systemPrompt: VERIFIED_RETAIL_PRICING_PROMPT,
    userPromptTemplate: [
      "Verify each candidate price using the strict retail pricing rules.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      part_number: "",
      model_number: null,
      verified_prices: [
        {
          source: "",
          url: "",
          sell_price: null,
          list_price: null,
          currency: "USD",
          verified: false,
          verification_reason: "",
        },
      ],
    },
  },
  {
    id: "ebay-listing-prep",
    name: "eBay Listing Prep",
    type: "ebay_listing_prep",
    description: "Prepare human-reviewable eBay listing drafts from validated inventory rows.",
    requiredInputs: ["brand", "modelNumber", "partNumber", "quantity", "photoIds", "conditionNote", "price"],
    enabled: true,
    systemPrompt: [
      "You are an eBay listing draft assistant for appliance inventory.",
      "Return only valid JSON.",
      "Do not mark a listing ready unless all validation requirements are satisfied.",
      "Drafts are for human review only.",
    ].join("\n"),
    userPromptTemplate: [
      "Prepare a listing draft from validated inventory data.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      readyForReview: false,
      blockingIssues: [],
      listingDraft: {
        title: null,
        description: null,
        sku: null,
        price: null,
        quantity: null,
        condition: null,
        photoIds: [],
      },
    },
  },
  {
    id: "market-intelligence-survey",
    name: "Pricing And Listing Survey",
    type: "market_intelligence_survey",
    description: "Collect pricing and listing signals in a structured, review-first flow.",
    requiredInputs: ["modelNumber", "brand", "targetMarket"],
    enabled: true,
    systemPrompt: [
      "You are a pricing and listing survey agent.",
      "Collect source-backed market signals for the specified model and part context.",
      "Return structured data for operator review before any listing action.",
      "Do not claim publish-ready status without explicit verification fields.",
    ].join("\n"),
    userPromptTemplate: [
      "Run a pricing and listing survey for the specified model and brand.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      marketSignals: {
        averagePrice: null,
        competitorCount: 0,
        demandLevel: "unknown",
        recommendedPrice: null,
        listingStrategy: "",
      },
    },
  },
  {
    id: "visual-loop-recovery",
    name: "Visual Loop Recovery",
    type: "visual_loop_recovery",
    description: "Automatically navigate past security gates or dynamic UI blocks using visual analysis.",
    requiredInputs: ["browserViewport", "domState", "blockedReason"],
    enabled: true,
    systemPrompt: [
      "Goal: Automatically navigate past security gates or dynamic UI blocks.",
      "Detect 403/429 or \"Wait\" screens.",
      "Analyze visually. If Captcha: Prompt HITL.",
      "If UI Popup: Use Computer Use to click 'X'.",
      "Self-correct via Instruction Patching.",
    ].join("\n"),
    userPromptTemplate: [
      "Perform a visual loop recovery for the specified block context.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      action: "click",
      coordinates: { x: 0, y: 0 },
      reason: "",
      needsHITL: false,
    },
  },
  {
    id: "may7-rld-orchestration-phase-1a",
    name: "May 7 RLD Orchestration Phase 1A",
    type: "may7_rld_orchestration_phase_1a",
    description: "Read-only project reference shape and state lock template from the May 7 RLD prompt pack.",
    requiredInputs: ["projectGoal", "constraints", "files", "screenshots", "schemas", "userDefinedTerms"],
    enabled: true,
    systemPrompt: MAY7_RLD_ORCHESTRATION_PHASE_1A_PROMPT,
    userPromptTemplate: [
      "Run the May 7 RLD orchestration lock contract against the supplied project materials.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      sections: [
        "PROJECT GOAL ID (lock)",
        "REFERENCE STATE ID (lock)",
        "SUCCESS STATE ID (lock)",
        "CONSTRAINT ID (lock)",
        "LOCK CANDIDATES",
        "FORBIDDEN DELTA",
        "AMBIGUITY REGISTER",
        "SOURCE OF TRUTH FIELD DRAFT",
        "LOCK READINESS VERDICT",
      ],
    },
  },
  {
    id: "may7-rld-unified-image-tattoo-lock-extraction",
    name: "May 7 Unified Image / Tattoo Lock Extraction",
    type: "may7_unified_image_tattoo_lock_extraction",
    description: "Read-only visual lock extraction template from the May 7 RLD prompt pack.",
    requiredInputs: ["referenceImage", "visibleContext"],
    enabled: true,
    systemPrompt: MAY7_UNIFIED_IMAGE_TATTOO_LOCK_EXTRACTION_PROMPT,
    userPromptTemplate: [
      "Run the May 7 unified reference-first lock extraction contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      sections: [
        "DESIGN ID (lock)",
        "STYLE ID (lock)",
        "CONTEXT ID (lock)",
        "CAMERA ID (lock)",
        "COMPOSITION ID (lock)",
        "TATTOO ID (lock)",
        "PLACEMENT ID (lock)",
      ],
    },
  },
  {
    id: "may7-rld-tattoo-surgical-edit",
    name: "May 7 Tattoo Surgical Edit",
    type: "may7_tattoo_surgical_edit",
    description: "Bounded zero-drift tattoo edit template from the May 7 RLD prompt pack.",
    requiredInputs: ["baseImage", "activeLocks", "delta"],
    enabled: true,
    systemPrompt: MAY7_TATTOO_SURGICAL_EDIT_PROMPT,
    userPromptTemplate: [
      "Run the May 7 tattoo surgical edit contract with the supplied base image, locks, and delta.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      output: "one edited image only",
      sections: ["SOURCE OF TRUTH LOCK", "CANVAS LOCK", "DESIGN / IDENTITY LOCK", "DELTA LOCK"],
    },
  },
  {
    id: "may7-rld-tattoo-flash-variant-sheet",
    name: "May 7 Tattoo Flash / Variant Sheet",
    type: "may7_tattoo_flash_variant_sheet",
    description: "Trace-ready tattoo variant sheet template from the May 7 RLD prompt pack.",
    requiredInputs: ["referenceImage", "activeLocks", "outputFormat"],
    enabled: true,
    systemPrompt: MAY7_TATTOO_FLASH_VARIANT_SHEET_PROMPT,
    userPromptTemplate: [
      "Run the May 7 tattoo flash / variant sheet contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      output: "single 3-panel sheet or three separate outputs",
      sections: ["SOURCE OF TRUTH LOCK", "DESIGN LOCK", "STYLE LOCK", "VARIANT LOCKS"],
    },
  },
  {
    id: "may7-rld-roadrunner-identity-extraction",
    name: "May 7 Roadrunner Identity Extraction",
    type: "may7_roadrunner_identity_extraction",
    description: "Evidence-only appliance identity extraction template from the May 7 RLD prompt pack.",
    requiredInputs: ["imageEvidence", "manualText", "ocrEvidence"],
    enabled: true,
    systemPrompt: MAY7_ROADRUNNER_IDENTITY_EXTRACTION_PROMPT,
    userPromptTemplate: [
      "Extract the appliance identity fields from the supplied evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      model: null,
      serial: null,
      appliance_type: null,
      fuel_type: null,
      voltage_or_power_clues: [],
      type_code: null,
      confidence: 0,
      uncertain_fields: [],
      rejected_candidates: [],
    },
  },
  {
    id: "may7-rld-roadrunner-orchestrator",
    name: "May 7 Roadrunner Orchestrator",
    type: "may7_roadrunner_orchestrator",
    description: "Read-only BOM workflow state router template from the May 7 RLD prompt pack.",
    requiredInputs: ["modelNumber", "identityState", "jobState", "validatorState"],
    enabled: true,
    systemPrompt: MAY7_ROADRUNNER_ORCHESTRATOR_PROMPT,
    userPromptTemplate: [
      "Identify the next required agent stage from the supplied job state only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      nextStage: "NAMEPLATE_INGEST",
      reason: "",
      requiredInputs: [],
      blocked: false,
      blockers: [],
    },
  },
  {
    id: "may7-rld-roadrunner-parts-extraction",
    name: "May 7 Roadrunner Parts Extraction",
    type: "may7_roadrunner_parts_extraction",
    description: "Source-backed part row extraction template from the May 7 RLD prompt pack.",
    requiredInputs: ["model", "sourceEvidence", "sectionName", "sourceUrl"],
    enabled: true,
    systemPrompt: MAY7_ROADRUNNER_PARTS_EXTRACTION_PROMPT,
    userPromptTemplate: [
      "Extract verified appliance part rows from the supplied source evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      rows: [
        {
          section: "",
          diagramNumber: null,
          quantity: 1,
          originalPartNumber: null,
          currentServicePartNumber: null,
          description: "",
          nlaStatus: false,
          replacementNote: null,
          confidence: 0,
        },
      ],
    },
  },
  {
    id: "may7-rld-roadrunner-pricing-extraction",
    name: "May 7 Roadrunner Pricing Extraction",
    type: "may7_roadrunner_pricing_extraction",
    description: "Visible retail price evidence extraction template from the May 7 RLD prompt pack.",
    requiredInputs: ["partNumbers", "approvedSources", "visiblePriceEvidence"],
    enabled: true,
    systemPrompt: MAY7_ROADRUNNER_PRICING_EXTRACTION_PROMPT,
    userPromptTemplate: [
      "Extract verified retail pricing from the supplied visible source evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      enrichments: [
        {
          partNumber: "",
          price: null,
          priceSource: null,
          sourceUrl: null,
          matchType: "no_match",
          confidence: 0,
        },
      ],
    },
  },
  {
    id: "may7-rld-roadrunner-final-bom-audit",
    name: "May 7 Roadrunner Final BOM Audit",
    type: "may7_roadrunner_final_bom_audit",
    description: "Read-only BOM readiness audit template from the May 7 RLD prompt pack.",
    requiredInputs: ["validatorOutput", "partsState", "pricingState"],
    enabled: true,
    systemPrompt: MAY7_ROADRUNNER_FINAL_BOM_AUDIT_PROMPT,
    userPromptTemplate: [
      "Summarize BOM readiness from validator results without creating evidence.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      retrievalState: "audit_blocked",
      partsComplete: false,
      pricingComplete: false,
      bomComplete: false,
      expectedPartCount: null,
      actualPartCount: null,
      verifiedPriceCount: null,
      blockers: [],
    },
  },
  {
    id: "may7-rld-roadrunner-diagnostic",
    name: "May 7 Roadrunner Diagnostic",
    type: "may7_roadrunner_diagnostic",
    description: "Evidence-bound appliance diagnostic review template from the May 7 RLD prompt pack.",
    requiredInputs: ["applianceIdentity", "symptoms", "fieldNotes", "images", "video", "audio", "errorCodes"],
    enabled: true,
    systemPrompt: MAY7_ROADRUNNER_DIAGNOSTIC_PROMPT,
    userPromptTemplate: [
      "Analyze the supplied diagnostic evidence and return the structured diagnostic output.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      observedSymptoms: [],
      likelyFaultAreas: [
        {
          system: "",
          likelyParts: [],
          confidence: 0,
          evidence: [],
        },
      ],
      nextChecks: [],
      serviceModeChecks: [],
      safetyWarnings: [],
      missingEvidence: [],
    },
  },
  {
    id: "may7-rld-global-prompt-rule",
    name: "May 7 Global RLD Prompt Rule",
    type: "may7_global_rld_prompt_rule",
    description: "Global RLD prompt rubric from the May 7 prompt pack.",
    requiredInputs: ["promptDraft"],
    enabled: true,
    systemPrompt: MAY7_GLOBAL_RLD_PROMPT_RULE,
    userPromptTemplate: [
      "Apply the global May 7 RLD prompt rule to the supplied prompt draft.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      sections: [
        "TOOL ROUTING",
        "MODE",
        "TASK",
        "RULES",
        "OUTPUT CONSTRAINTS",
        "LOCK SECTIONS",
        "FAIL-SAFE",
        "DOWNSTREAM USE STATEMENT",
      ],
    },
  },
];

export function getPromptScenarioById(id: string) {
  return PROMPT_SCENARIOS.find((scenario) => scenario.id === id) || null;
}

export function getPromptScenarioByType(type: PromptScenario["type"]) {
  return PROMPT_SCENARIOS.find((scenario) => scenario.type === type) || null;
}
