import type { PromptScenario } from "./types";
import {
  BOM_ROW_EXTRACTION_JSON_PROMPT,
  COMPUTER_USE_NAVIGATION_PROMPT,
  NAMEPLATE_OCR_IDENTITY_JSON_PROMPT,
  OFFICIAL_PARTS_SOURCE_SEARCH_PROMPT,
  PLAINTEXT_IDENTITY_EXTRACTOR_PROMPT,
  PRICING_ROUTER_PROMPT,
  TECHNICAL_DIAGRAM_CALLOUT_CSV_PROMPT,
  VERIFIED_RETAIL_PRICING_PROMPT,
  VISUAL_QA_DRIFT_JSON_PROMPT,
} from "../prompts/strict-scenarios";

export const PROMPT_SCENARIOS: PromptScenario[] = [
  {
    id: "identity-extraction",
    name: "Identity Extraction",
    type: "identity_extraction",
    description: "Extract appliance identity from OCR, manual, supplier, or operator-entered evidence.",
    requiredInputs: ["imageOcrText", "manualText", "knownSupplierResult", "userEnteredModelNumber"],
    enabled: true,
    systemPrompt: [
      "You are a strict appliance identity extraction agent.",
      "Return only valid JSON.",
      "Do not infer brand, model, serial, product type, or engineering code unless evidence supports it.",
      "Use null for unknown values and include confidence by field.",
    ].join("\n"),
    userPromptTemplate: [
      "Extract brand, model number, serial number, product type, engineering code, confidence, and candidates.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      modelNumber: null,
      serialNumber: null,
      productType: null,
      engineeringCode: null,
      confidence: {
        brand: 0,
        modelNumber: 0,
        serialNumber: 0,
        productType: 0,
        engineeringCode: 0,
      },
      candidates: [],
    },
  },
  {
    id: "nameplate-ocr-identity-json",
    name: "Nameplate OCR Identity Extraction",
    type: "nameplate_ocr_identity_json",
    description: "Extract only visible brand, product type, model number, and serial number from one nameplate image.",
    requiredInputs: ["nameplateImage"],
    enabled: true,
    systemPrompt: NAMEPLATE_OCR_IDENTITY_JSON_PROMPT,
    userPromptTemplate: [
      "Run the strict nameplate OCR identity extraction contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      productType: null,
      modelNumber: null,
      serialNumber: null,
    },
  },
  {
    id: "plaintext-identity-extractor",
    name: "Plaintext Identity Extractor",
    type: "plaintext_identity_extraction",
    description: "Convert plaintext appliance evidence into a bounded RoadrunnerParts identity object.",
    requiredInputs: ["plaintextEvidence"],
    enabled: true,
    systemPrompt: PLAINTEXT_IDENTITY_EXTRACTOR_PROMPT,
    userPromptTemplate: [
      "Extract identity from the supplied plaintext evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      brand: null,
      model: null,
      serial: null,
      type_code: null,
      appliance_type: null,
      fuel_type: null,
      voltage_or_power_clues: [],
    },
  },
  {
    id: "supplier-url-generation",
    name: "Supplier URL Generation",
    type: "supplier_url_generation",
    description: "Convert brand/model context into supplier-specific candidate URLs.",
    requiredInputs: ["brand", "modelNumber", "supplier", "knownUrlRules"],
    enabled: true,
    systemPrompt: [
      "You are a supplier URL planning agent.",
      "Return only valid JSON.",
      "Do not browse or claim a URL is live unless the input evidence proves it.",
      "Treat URLs as candidates for later operator review.",
    ].join("\n"),
    userPromptTemplate: [
      "Generate supplier-specific search URLs and canonical model URL candidates.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      supplier: "encompass",
      brandCode: null,
      normalizedModel: null,
      candidateUrls: [],
      confidence: 0,
      notes: [],
    },
  },
  {
    id: "official-parts-source-search",
    name: "Official Parts Source Search",
    type: "official_parts_source_search",
    description: "Select one verified model-specific URL from a target supplier domain.",
    requiredInputs: ["modelNumber", "targetSupplierDomain"],
    enabled: true,
    systemPrompt: OFFICIAL_PARTS_SOURCE_SEARCH_PROMPT,
    userPromptTemplate: [
      "Identify the single best model-specific URL from the target domain.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: "https://target-domain.example/model-specific-url",
  },
  {
    id: "diagram-discovery",
    name: "Diagram Discovery",
    type: "diagram_discovery",
    description: "Plan diagram section discovery from source context without extracting final parts.",
    requiredInputs: ["modelNumber", "supplier", "sourceUrl", "browserCapture"],
    enabled: true,
    systemPrompt: [
      "You are a diagram discovery reviewer.",
      "Return only valid JSON.",
      "Use only supplied source context.",
      "Do not create final BOM rows or part-number claims.",
    ].join("\n"),
    userPromptTemplate: [
      "Find diagram sections and source URLs from the supplied evidence.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      modelNumber: null,
      supplier: null,
      diagrams: [
        {
          sectionName: null,
          diagramUrl: null,
          sourceUrl: null,
          confidence: 0,
        },
      ],
    },
  },
  {
    id: "technical-diagram-callouts-csv",
    name: "Technical Diagram Extraction",
    type: "technical_diagram_callouts_csv",
    description: "Extract a top-left sheet title and unique visible numeric callouts from one technical diagram image as CSV.",
    requiredInputs: ["diagramImage"],
    enabled: true,
    systemPrompt: TECHNICAL_DIAGRAM_CALLOUT_CSV_PROMPT,
    userPromptTemplate: [
      "Run the strict technical diagram extraction contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: "Sheet_Title,Callout_Number\nFRONT PANEL & DOOR,313",
  },
  {
    id: "visual-qa-drift-json",
    name: "Visual QA Drift Check",
    type: "visual_qa_drift_json",
    description: "Read-only comparison of a candidate generated image against a base reference image.",
    requiredInputs: ["baseReferenceImage", "candidateGeneratedImage"],
    enabled: true,
    systemPrompt: VISUAL_QA_DRIFT_JSON_PROMPT,
    userPromptTemplate: [
      "Run the read-only visual QA and design drift check.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      passed: false,
      major_drift_detected: false,
      added_elements: [],
      missing_elements: [],
      altered_elements: [],
      proportion_changes: [],
      notes: [],
    },
  },
  {
    id: "computer-use-navigation",
    name: "Computer-Use UI Navigation",
    type: "computer_use_navigation",
    description: "Navigate a current browser/DOM state to an assembly page and return the first three visible parts, or a blocked reason.",
    requiredInputs: ["browserViewport", "domState", "modelPageUrl"],
    enabled: true,
    systemPrompt: COMPUTER_USE_NAVIGATION_PROMPT,
    userPromptTemplate: [
      "Run the deterministic UI navigation contract.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: "1. Exact visible part text\n2. Exact visible part text\n3. Exact visible part text",
  },
  {
    id: "bom-extraction",
    name: "BOM Extraction",
    type: "bom_extraction",
    description: "Extract source-backed part rows from supplied provider/manual evidence only.",
    requiredInputs: ["modelNumber", "supplier", "sourceUrl", "diagramContext", "sourceEvidence"],
    enabled: true,
    systemPrompt: [
      "You are a source-backed BOM extraction agent.",
      "Return only valid JSON.",
      "Final part rows must come from supplied provider evidence, captured JSON, manuals, or database records.",
      "Do not treat prompts, appliance architecture, or guesses as source evidence.",
    ].join("\n"),
    userPromptTemplate: [
      "Extract part title, part number, quantity, diagram key, assembly section, source URL, and evidence text.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      modelNumber: null,
      supplier: null,
      parts: [
        {
          partNumber: null,
          partTitle: null,
          quantity: null,
          diagramKey: null,
          assemblySection: null,
          sourceUrl: null,
          evidenceText: null,
          confidence: 0,
        },
      ],
      completeness: {
        expectedCount: null,
        actualCount: 0,
        status: "no_result",
      },
    },
  },
  {
    id: "bom-row-extraction-json",
    name: "BOM Row Extraction JSON",
    type: "bom_row_extraction_json",
    description: "Extract model-specific BOM rows from supplied model, diagram, and pricing evidence without inventing missing data.",
    requiredInputs: ["modelSpecificPartsEvidence", "diagramCalloutEvidence", "pricingEvidence"],
    enabled: true,
    systemPrompt: BOM_ROW_EXTRACTION_JSON_PROMPT,
    userPromptTemplate: [
      "Extract strict source-backed BOM rows from the supplied evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      model_number: "",
      appliance_type: null,
      bom_rows: [
        {
          sheet_title: null,
          callout_number: null,
          part_number: null,
          part_title: null,
          quantity: null,
          price: null,
          availability: null,
          source_name: "",
          source_url: null,
          confidence: "model_confirmed",
        },
      ],
    },
  },
  {
    id: "bom-validation",
    name: "BOM Validation",
    type: "bom_validation",
    description: "Validate rows before database, export, pricing, or listing actions.",
    requiredInputs: ["brand", "modelNumber", "rows", "retrievalStatus"],
    enabled: true,
    systemPrompt: [
      "You are a BOM validation gate.",
      "Return only valid JSON.",
      "Do not repair rows by inventing missing evidence.",
      "Reject rows missing source URL or required part identity.",
    ].join("\n"),
    userPromptTemplate: [
      "Validate extracted rows before anything enters a database or export pipeline.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      valid: false,
      errors: [],
      warnings: [],
      acceptedRows: [],
      rejectedRows: [],
    },
  },
  {
    id: "pricing-reconciliation",
    name: "Pricing Reconciliation",
    type: "pricing_reconciliation",
    description: "Attach supplier pricing only after BOM rows are validated.",
    requiredInputs: ["partNumber", "supplier", "validatedBomRow", "pricingSourceEvidence"],
    enabled: true,
    systemPrompt: [
      "You are a pricing reconciliation agent.",
      "Return only valid JSON.",
      "Do not price unvalidated BOM rows.",
      "Do not invent price, availability, or supplier evidence.",
    ].join("\n"),
    userPromptTemplate: [
      "Attach supplier pricing from supplied pricing evidence only.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      partNumber: null,
      supplier: null,
      price: null,
      availability: null,
      sourceUrl: null,
      confidence: 0,
    },
  },
  {
    id: "pricing-router",
    name: "Fallback Pricing Router",
    type: "pricing_router",
    description: "Choose the best pricing source tier using the strict fallback order.",
    requiredInputs: ["brand", "modelNumber", "partNumber", "supplierList"],
    enabled: true,
    systemPrompt: PRICING_ROUTER_PROMPT,
    userPromptTemplate: [
      "Choose the selected pricing source tier and explain the source-bound reason.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      selected_tier: null,
      selected_source: null,
      reason: "",
    },
  },
  {
    id: "verified-retail-pricing",
    name: "Verified Retail Pricing",
    type: "retail_pricing_verification",
    description: "Verify candidate retail prices against exact part and model context.",
    requiredInputs: ["partNumber", "modelNumber", "candidatePricingSources"],
    enabled: true,
    systemPrompt: VERIFIED_RETAIL_PRICING_PROMPT,
    userPromptTemplate: [
      "Verify each candidate price using the strict retail pricing rules.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      part_number: "",
      model_number: null,
      verified_prices: [
        {
          source: "",
          url: "",
          sell_price: null,
          list_price: null,
          currency: "USD",
          verified: false,
          verification_reason: "",
        },
      ],
    },
  },
  {
    id: "ebay-listing-prep",
    name: "eBay Listing Prep",
    type: "ebay_listing_prep",
    description: "Prepare human-reviewable eBay listing drafts from validated inventory rows.",
    requiredInputs: ["brand", "modelNumber", "partNumber", "quantity", "photoIds", "conditionNote", "price"],
    enabled: true,
    systemPrompt: [
      "You are an eBay listing draft assistant for appliance inventory.",
      "Return only valid JSON.",
      "Do not mark a listing ready unless all validation requirements are satisfied.",
      "Drafts are for human review only.",
    ].join("\n"),
    userPromptTemplate: [
      "Prepare a listing draft from validated inventory data.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      readyForReview: false,
      blockingIssues: [],
      listingDraft: {
        title: null,
        description: null,
        sku: null,
        price: null,
        quantity: null,
        condition: null,
        photoIds: [],
      },
    },
  },
  {
    id: "market-intelligence-survey",
    name: "Market Intelligence Survey",
    type: "market_intelligence_survey",
    description: "Orchestrate an eBay market survey and listing preparation mission.",
    requiredInputs: ["modelNumber", "brand", "targetMarket"],
    enabled: true,
    systemPrompt: [
      "You are a Market Intelligence Agent.",
      "Your mission is to survey the current market for appliance parts on eBay.",
      "Analyze pricing trends, competitor listings, and sell-through rates.",
      "Return structured market signals for listing optimization.",
    ].join("\n"),
    userPromptTemplate: [
      "Perform a market survey for the specified model and brand.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      marketSignals: {
        averagePrice: null,
        competitorCount: 0,
        demandLevel: "unknown",
        recommendedPrice: null,
        listingStrategy: "",
      },
    },
  },
  {
    id: "visual-loop-recovery",
    name: "Visual Loop Recovery",
    type: "visual_loop_recovery",
    description: "Automatically navigate past security gates or dynamic UI blocks using visual analysis.",
    requiredInputs: ["browserViewport", "domState", "blockedReason"],
    enabled: true,
    systemPrompt: [
      "Goal: Automatically navigate past security gates or dynamic UI blocks.",
      "Detect 403/429 or \"Wait\" screens.",
      "Analyze visually. If Captcha: Prompt HITL.",
      "If UI Popup: Use Computer Use to click 'X'.",
      "Self-correct via Instruction Patching.",
    ].join("\n"),
    userPromptTemplate: [
      "Perform a visual loop recovery for the specified block context.",
      "Input payload:",
      "{{input_payload_json}}",
    ].join("\n\n"),
    expectedJsonShape: {
      action: "click",
      coordinates: { x: 0, y: 0 },
      reason: "",
      needsHITL: false,
    },
  },
];

export function getPromptScenarioById(id: string) {
  return PROMPT_SCENARIOS.find((scenario) => scenario.id === id) || null;
}

export function getPromptScenarioByType(type: PromptScenario["type"]) {
  return PROMPT_SCENARIOS.find((scenario) => scenario.type === type) || null;
}
